services:
  web:
    labels:
      - "traefik.http.routers.myapp.rule=Host(`srv726877.hstgr.cloud`)"
      - "traefik.http.routers.myapp.tls.certresolver=myresolver"
    #security_opt:
      #- seccomp=./seccomp.json
    build: .
    ports:
      - "8000:8000"
    restart: unless-stopped
